---
- name: Install Firefox
  hosts: aviservers
  tasks:
    - name: Install Firefox from exe
      win_package:
        path: https://download-installer.cdn.mozilla.net/pub/firefox/releases/68.0/win64/en-US/Firefox%20Setup%2068.0.exe
        product_id: 'Mozilla Firefox'
        state: present
        arguments: '-ms /INI=C:\Temp\firefox\mInstall.ini'